Upgrade provider to `~>4.1`
mineiros-io/terraform-google-gke-cluster pull request #11
Opened 2021-12-10 18:46 UTC by soerenmartius

2021-12-13 18:34 UTC, mariux requested changes

2021-12-13 18:34 UTC, mariux commented on CHANGELOG.md
> +- Delete `resource "google_project_service` resource
```suggestion
- Remove support for `google_project_service` resource
```

2021-12-14 02:23 UTC, soerenmartius commented on CHANGELOG.md
> +- Delete `resource "google_project_service` resource
resolved in 4128978d

2021-12-14 02:23 UTC, soerenmartius commented on CHANGELOG.md
> +- Delete `resource "google_project_service` resource
resolved in 4128978d

2021-12-16 14:19 UTC, thiesen approved these changes
lgtm!

2021-12-16 14:26 UTC, merged